from enum import StrEnum

class AllureTag(StrEnum):
    AUTHENTICATION = 'AUTHENTICATION'
    COURSES = 'COURSES'
    EXERCISES = 'EXERCISES'
    FILES = 'FILES'
    REGRESSION = 'REGRESSION'
    USERS = 'USERS'

    GET_ENTITY = 'GET_ENTITY'
    GET_ENTITIES = 'GET_ENTITIES'
    CREATE_ENTITY = 'CREATE_ENTITY'
    UPDATE_ENTITY = 'UPDATE_ENTITY'
    DELETE_ENTITY = 'DELETE_ENTITY'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
